mq:
   host: localhost
   username: guest
   password: guest
   port: 5672
   vhost: /
   exchange:
      name: parse_file_exchange
      durable: true
      autoDelete: false
 
   queue:
      name: parse_file_queue
      durable: true
      exclusive: false
      autoDelete: false
 
   routekey: parse_file_routekey